import {
  amber,
  amberDark,
  grass,
  grassDark,
  gray,
  grayDark,
  indigo,
  indigoDark,
  tomato,
  tomatoDark,
  violet,
  violetDark,
  whiteA,
} from '@radix-ui/colors'

import { createStitches } from '@stitches/react'

export const {
  styled,
  css,
  getCssText,
  config,
  globalCss: stitchesGlobal,
  theme,
  keyframes,
  createTheme,
} = createStitches({
  theme: {
    colors: {
      ...gray,
      ...violet,
      ...tomato,
      ...grass,
      ...indigo,
      ...amber,
      ...whiteA,

      accentBase: '$violet1',
      accentBgSubtle: '$violet2',
      accentBg: '$violet3',
      accentBgHover: '$violet4',
      accentBgActive: '$violet5',
      accentLine: '$violet6',
      accentBorder: '$violet7',
      accentBorderHover: '$violet8',
      accentSolid: '$violet9',
      accentSolidHover: '$violet10',
      accentText: '$violet11',
      accentTextContrast: '$violet12',

      successBase: '$grass1',
      successBgSubtle: '$grass2',
      successBg: '$grass3',
      successBgHover: '$grass4',
      successBgActive: '$grass5',
      successLine: '$grass6',
      successBorder: '$grass7',
      successBorderHover: '$grass8',
      successSolid: '$grass9',
      successSolidHover: '$grass10',
      successText: '$grass11',
      successTextContrast: '$grass12',

      infoBase: '$indigo1',
      infoBgSubtle: '$indigo2',
      infoBg: '$indigo3',
      infoBgHover: '$indigo4',
      infoBgActive: '$indigo5',
      infoLine: '$indigo6',
      infoBorder: '$indigo7',
      infoBorderHover: '$indigo8',
      infoSolid: '$indigo9',
      infoSolidHover: '$indigo10',
      infoText: '$indigo11',
      infoTextContrast: '$indigo12',

      warningBase: '$amber1',
      warningBgSubtle: '$amber2',
      warningBg: '$amber3',
      warningBgHover: '$amber4',
      warningBgActive: '$amber5',
      warningLine: '$amber6',
      warningBorder: '$amber7',
      warningBorderHover: '$amber8',
      warningSolid: '$amber9',
      warningSolidHover: '$amber10',
      warningText: '$amber11',
      warningTextContrast: '$amber12',

      dangerBase: '$tomato1',
      dangerBgSubtle: '$tomato2',
      dangerBg: '$tomato3',
      dangerBgHover: '$tomato4',
      dangerBgActive: '$tomato5',
      dangerLine: '$tomato6',
      dangerBorder: '$tomato7',
      dangerBorderHover: '$tomato8',
      dangerSolid: '$tomato9',
      dangerSolidHover: '$tomato10',
      dangerText: '$tomato11',
      dangerTextContrast: '$tomato12',
    },
    space: {
      0: '0px',
      1: '4px',
      2: '8px',
      3: '12px',
      4: '16px',
      5: '20px',
      6: '24px',
      7: '32px',
      8: '40px',
      9: '48px',
      10: '56px',
      11: '80px',
      12: '96px',
      modal: '120px',
    },
    fontSizes: {
      h1: '44px',
      h2: '36px',
      h3: '28px',
      h4: '20px',
      h5: '18px',
      button: '16px',
      body: '14px',
      caption: '12px',
      small: '10px',
    },
    lineHeights: {
      h1: '48px',
      h2: '40px',
      h3: '32px',
      h4: '24px',
      h5: '24px',
      button: '24px',
      body: '24px',
      caption: '16px',
      small: '16px',
    },
    fonts: {
      default:
        '-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif',
      lato: 'Lato, sans-serif',
      devIcon: 'DevIcon',
    },
    fontWeights: {
      regular: 400,
      bold: 700,
      extraBold: 900,
    },
    letterSpacings: {},
    sizes: {
      1: '4px',
      2: '8px',
      3: '12px',
      4: '16px',
      5: '20px',
      6: '24px',
      7: '32px',
      8: '40px',
      9: '48px',
      10: '56px',
      11: '80px',
      12: '96px',
    },
    borderWidths: {
      1: '2px',
      2: '4px',
      3: '6px',
      4: '8px',
    },
    borderStyles: {},
    radii: {
      1: '4px',
      2: '8px',
      3: '12px',
      4: '16px',
      round: '50%',
    },
    shadows: {
      'elevation-100': '1px 1px 4px rgba(0, 30, 53, 0.1)',
      'elevation-200': '0px 8px 12px rgba(0, 30, 53, 0.05)',
      'border-default': 'inset 0 0 0 1px #CFCFD2',
      'border-hover': 'inset 0 0 0 2px #BFBFBF',
      'border-focus': 'inset 0 0 0 2px #84868C',
    },
    zIndices: {},
    transitions: {},
  },
  media: {
    sm: '(min-width: 520px)',
    md: '(min-width: 900px)',
    lg: '(min-width: 1080px)',
  },
  utils: {
    size: (value: string) => ({
      width: value,
      height: value,
    }),
    paddingX: (value: string) => ({
      paddingLeft: value,
      paddingRight: value,
    }),
    paddingY: (value: string) => ({
      paddingTop: value,
      paddingBottom: value,
    }),
    marginX: (value: string) => ({
      marginLeft: value,
      marginRight: value,
    }),
    marginY: (value: string) => ({
      marginTop: value,
      marginBottom: value,
    }),
  },
})

export const darkTheme = createTheme({
  colors: {
    ...grayDark,
    ...violetDark,
    ...tomatoDark,
    ...grassDark,
    ...indigoDark,
    ...amberDark,

    accentBase: '$violet1',
    accentBgSubtle: '$violet2',
    accentBg: '$violet3',
    accentBgHover: '$violet4',
    accentBgActive: '$violet5',
    accentLine: '$violet6',
    accentBorder: '$violet7',
    accentBorderHover: '$violet8',
    accentSolid: '$violet9',
    accentSolidHover: '$violet10',
    accentText: '$violet11',
    accentTextContrast: '$violet12',

    successBase: '$grass1',
    successBgSubtle: '$grass2',
    successBg: '$grass3',
    successBgHover: '$grass4',
    successBgActive: '$grass5',
    successLine: '$grass6',
    successBorder: '$grass7',
    successBorderHover: '$grass8',
    successSolid: '$grass9',
    successSolidHover: '$grass10',
    successText: '$grass11',
    successTextContrast: '$grass12',

    infoBase: '$indigo1',
    infoBgSubtle: '$indigo2',
    infoBg: '$indigo3',
    infoBgHover: '$indigo4',
    infoBgActive: '$indigo5',
    infoLine: '$indigo6',
    infoBorder: '$indigo7',
    infoBorderHover: '$indigo8',
    infoSolid: '$indigo9',
    infoSolidHover: '$indigo10',
    infoText: '$indigo11',
    infoTextContrast: '$indigo12',

    warningBase: '$amber1',
    warningBgSubtle: '$amber2',
    warningBg: '$amber3',
    warningBgHover: '$amber4',
    warningBgActive: '$amber5',
    warningLine: '$amber6',
    warningBorder: '$amber7',
    warningBorderHover: '$amber8',
    warningSolid: '$amber9',
    warningSolidHover: '$amber10',
    warningText: '$amber11',
    warningTextContrast: '$amber12',

    dangerBase: '$tomato1',
    dangerBgSubtle: '$tomato2',
    dangerBg: '$tomato3',
    dangerBgHover: '$tomato4',
    dangerBgActive: '$tomato5',
    dangerLine: '$tomato6',
    dangerBorder: '$tomato7',
    dangerBorderHover: '$tomato8',
    dangerSolid: '$tomato9',
    dangerSolidHover: '$tomato10',
    dangerText: '$tomato11',
    dangerTextContrast: '$tomato12',
  },
})

export const globalStyles = stitchesGlobal({
  '*': {
    boxSizing: 'border-box',
  },

  'ul,li': {
    listStyle: 'none',
  },

  a: {
    color: 'inherit',
    textDecoration: 'none',
  },

  body: {
    fontFamily: '$lato',
    padding: 0,
    margin: 0,
    backgroundColor: '$background-default',
  },
  '@font-face': {
    fontFamily: 'DevIcon',
    src: 'url("/fonts/devicon.ttf")',
  },
  '@import': 'url("https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&display=swap")',

  ':root': {},
})

export type ColorTokens = keyof typeof theme.colors
export type SizeTokens = keyof typeof theme.sizes
export type SpaceTokens = keyof typeof theme.space
